default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: airbnb-clone-9thweek
  host: localhost
  user: postgres
  password: 123456